language: csharp 
solution: Maths.sln 
install: 
   - nuget restore Maths.sln 
   - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner 
script: 
  - xbuild /p:Configuration=Release Maths.sln 
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Maths.Test/bin/Release/Maths.Test.dll 
 deploy:
   edge: true
   provider: cloudfoundry
   username: rayar.x.kaliyamoorthy@verizon.com
   password: {5&0}K-88NH{
   api: https://api.beta.ironfoundry.me
   organization: rayar
   space: staging
travis encrypt --add deploy.password

